version: '2'

services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    #ports:
    #  - '9000:9000'
    #  - '9001:9001'
    volumes:
      - ./minio-data:/data
    networks:
      - codepush-net

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - codepush-net

networks:
  codepush-net:
    external: true
